# Generated by Django 4.2.3 on 2023-07-20 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_chats'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_users',
            name='permitted_users',
            field=models.ManyToManyField(blank=True, related_name='permitted_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
