# Generated by Django 4.2.3 on 2023-07-20 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_chat_users_permitted_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_users',
            name='permitted_users',
        ),
        migrations.RemoveField(
            model_name='user',
            name='chats',
        ),
    ]
